## Numpy Indexing and Selection

In [1]:
import numpy as np

In [3]:
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[7]

7

In [5]:
arr[1:5]      # Inclusive start, exclusive end

array([1, 2, 3, 4])

In [6]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [7]:
arr[6:]

array([6, 7, 8, 9])

In [8]:
arr[0:4] = 100  # This is called broadcasting. Python list can NOT do this.

In [9]:
arr

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9])

### Numpy does not automatically copy an array unless said

In [11]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
slice_of_arr = arr[0:5]
slice_of_arr

array([0, 1, 2, 3, 4])

In [17]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99])

In [18]:
arr  # We can see the change in this original array

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

#### This is done because of memory issues with very large array. 
#### Numpy will not automatically copy an array

### Copying an Array

In [19]:
arr_copy = arr.copy()  # That's how I copy this
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [20]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [21]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

#### So the original array is intact

### Fun with matrix

In [23]:
arr_2d = np.array([[5, 2, 10], [2, 4, 10], [12, 23, 15]])
arr_2d

array([[ 5,  2, 10],
       [ 2,  4, 10],
       [12, 23, 15]])

##### General format of grabbing elements from a matrix
 1. Double bracket
 2. Single bracket with a comma (recommended)

##### Double Bracket Format

In [25]:
arr_2d[0][0]   # [row][column]

5

In [26]:
arr_2d[0]

array([ 5,  2, 10])

In [28]:
arr_2d[:][2]

array([12, 23, 15])

In [29]:
arr_2d

array([[ 5,  2, 10],
       [ 2,  4, 10],
       [12, 23, 15]])

In [31]:
# I want to get 23
arr_2d[2][1]

23

In [32]:
arr_2d[2, 1]    # This is recommended. Less prone to error

23

#### Grabbing certain section of the matrix

In [33]:
arr_2d[:2 , 1: ]

array([[ 2, 10],
       [ 4, 10]])

In [34]:
my_new = arr_2d[:2, 1:].copy()
my_new

array([[ 2, 10],
       [ 4, 10]])

In [37]:
arr_2d[ :2 , :]

array([[ 5,  2, 10],
       [ 2,  4, 10]])

### Conditional selection
    You are going to use this mostly

In [39]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [41]:
# This one is important
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

#### The following two do the same

In [42]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [43]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

## ----

In [45]:
my_arr = np.arange(50).reshape(5, 10)
my_arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [47]:
# I want to select 13, 14, 23, 24
my_arr[1:3, 3:5]

array([[13, 14],
       [23, 24]])